---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sumo-collector-healer
  namespace: sumo
  labels:
    app: sumo-collector-healer
data:
  ANSIBLE_CONNECTION: 'winrm'
  ANSIBLE_HOST_DOMAIN: 'example.com'
  ANSIBLE_PORT: '5985'
  ANSIBLE_STDOUT_CALLBACK: debug
  ANSIBLE_USER: 'MYDOMAIN\myuser'
  ANSIBLE_WINRM_SCHEME: 'http'
  ANSIBLE_WINRM_SERVER_CERT_VALIDATION: 'ignore'
  ANSIBLE_WINRM_TRANSPORT: 'ntlm'
  DOMAIN: example.com
  INTERVAL_SECONDS: '3600'
  PYTHONUNBUFFERED: "1"
  SUMO_ACCESS_ID: 'myid'
  SUMO_URL: 'https://api.us2.sumologic.com/api/v1/collectors'
